### ISSUE TITLE
Enhancement suggestion: STEP math

### ISSUE THREAD

**Issue by callegar** [dbenjaminmiller/step#4]
I'd like to suggest a STEP math and a STEP math bold font, derived from XITS. XITS Math is a good math companion for STEP, but now that XITS is no longer making releases, there is really no possibility to fix those remaining issues it has, like the very much too loose mathematical $f$ followed by a subscript  as in $f_H$ or $f_L$.

**Comment by callegar** [comment]
Incidentally, the README of the project suggests that STEP *includes support for OpenType mathematical typesetting, usable with LuaTeX, XeTeX and Microsoft Office*, but it is unclear to me how to take advantage of it. Trying to use STEP with LuaTeX and the `unicode-math` package via `\setmathfont` results in errors such as `Font "Step Regular" does not contain requested Script "Math"`.

**Comment by dbenjaminmiller** [comment]
Hi --- sorry, originally I actually did include STEP Math (virtually a copy of XITS). However, I removed it from the distribution as I felt it would be difficult to maintain and I think XITS is fine. I can add it back but I doubt I would be able to make much headway as I'm not great at modifying opentype math tables.

**Comment by callegar** [comment]
I think that it would be nice to re-add the math now that the XITS repo is archived. Even if at current time you cannot develop it this would let:
- have a place where pull requests from others can be merged
- issues can be tracked (currently I have opened https://github.com/callegar/xits-issues for this, but it is not the best thing).

**Comment by khaledhosny** [comment]
FWIW, I’m happy to transfer XITS repo to anyone who wants to maintain it. I also don’t use OFL RFN clause, so anyone is free to fork and use the same name (some users might not appreciation metric-incompatible changes, though).

**Comment by dbenjaminmiller** [comment]
If you'd like the original XITS, Sergio, since Khaled has offered to transfer ownership if you want to maintain it, I'd say have at it. I'm going to close this issue because I think I'm not the best person to maintain XITS-Math.
